package com.kiduyuk.klausk.kiduyutv.util

object AdUnitIds {
    // Google AdMob sample IDs. Keep these while testing so every request returns
    // a test ad and no live traffic is generated by development builds.
    private const val TEST_APP_OPEN = "ca-app-pub-3940256099942544/9257395921"
    private const val TEST_ADAPTIVE_BANNER = "ca-app-pub-3940256099942544/9214589741"
    private const val TEST_INTERSTITIAL = "ca-app-pub-3940256099942544/1033173712"
    private const val TEST_REWARDED = "ca-app-pub-3940256099942544/5224354917"
    private const val TEST_REWARDED_INTERSTITIAL = "ca-app-pub-3940256099942544/5354046379"
    private const val TEST_NATIVE = "ca-app-pub-3940256099942544/2247696110"

    // ── Phone (AdMob) ─────────────────────────────────────────────────────

    val PHONE_BANNER: String get() = TEST_ADAPTIVE_BANNER

    val PHONE_INTERSTITIAL: String get() = TEST_INTERSTITIAL

    val PHONE_REWARDED: String get() = TEST_REWARDED

    val PHONE_REWARDED_INTERSTITIAL: String get() = TEST_REWARDED_INTERSTITIAL

    val PHONE_APP_OPEN: String get() = TEST_APP_OPEN

    val PHONE_NATIVE: String get() = TEST_NATIVE

    // ── TV (AdMob) ────────────────────────────────────────────────────────

    val TV_BANNER: String get() = TEST_ADAPTIVE_BANNER

    val TV_INTERSTITIAL: String get() = TEST_INTERSTITIAL

    val TV_REWARDED_INTERSTITIAL: String get() = TEST_REWARDED_INTERSTITIAL

    val TV_APP_OPEN: String get() = TEST_APP_OPEN

    val TV_NATIVE: String get() = TEST_NATIVE
}
